export const dashboardData = [
  {
    id: 1,
    header: "Guest Arrival Experience",
    type: "Executive Summary",
    status: "Done",
    target: "24",
    limit: "12",
    reviewer: "Eddie Lake",
  },
  {
    id: 2,
    header: "Spa Service Optimization",
    type: "Technical Approach",
    status: "In Progress",
    target: "18",
    limit: "10",
    reviewer: "Emily Whalen",
  },
  {
    id: 3,
    header: "Room Upgrade Campaign",
    type: "Capabilities",
    status: "Done",
    target: "14",
    limit: "8",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 4,
    header: "Housekeeping Workflow",
    type: "Design",
    status: "In Progress",
    target: "20",
    limit: "9",
    reviewer: "Emily Whalen",
  },
  {
    id: 5,
    header: "Dining Reservation Plan",
    type: "Narrative",
    status: "Not Started",
    target: "16",
    limit: "7",
    reviewer: "Assign reviewer",
  },
  {
    id: 6,
    header: "Wellness Program Rollout",
    type: "Focus Documents",
    status: "Done",
    target: "11",
    limit: "5",
    reviewer: "Eddie Lake",
  },
  {
    id: 7,
    header: "VIP Check-In Process",
    type: "Cover Page",
    status: "In Progress",
    target: "21",
    limit: "11",
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: 8,
    header: "Guest Communication Pack",
    type: "Table of Contents",
    status: "Done",
    target: "9",
    limit: "4",
    reviewer: "Emily Whalen",
  },
]
